export const FETCH_REQUEST_LOG_REQUEST = "FETCH_REQUEST_LOG_REQUEST";
export const FETCH_REQUEST_LOG_SUCCESS = "FETCH_REQUEST_LOG_SUCCESS";
export const FETCH_REQUEST_LOG_FAILURE = "FETCH_REQUEST_LOG_FAILURE";
export const RESET_REQUEST_LOG = "RESET_REQUEST_LOG";
export const CLEAR_REQUEST_LOG = "CLEAR_REQUEST_LOG";

export const FETCH_REQUEST_VIEW_REQUEST = "FETCH_REQUEST_VIEW_REQUEST";
export const FETCH_REQUEST_VIEW_SUCCESS = "FETCH_REQUEST_VIEW_SUCCESS";
export const FETCH_REQUEST_VIEW_FAILURE = "FETCH_REQUEST_VIEW_FAILURE";
export const RESET_REQUEST_VIEW = "RESET_REQUEST_VIEW";

export const UPDATE_CERTIFICATE_REQUEST_REQUEST = "UPDATE_CERTIFICATE_REQUEST_REQUEST";
export const UPDATE_CERTIFICATE_REQUEST_SUCCESS = "UPDATE_CERTIFICATE_REQUEST_SUCCESS";
export const UPDATE_CERTIFICATE_REQUEST_FAILURE = "UPDATE_CERTIFICATE_REQUEST_FAILURE";
export const RESET_UPDATE_REQUEST = "RESET_UPDATE_REQUEST";
