export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_FROM_TOKEN_REQUEST = "GET_USER_FROM_TOKEN_REQUEST";
export const GET_USER_FROM_TOKEN_SUCCESS = "GET_USER_FROM_TOKEN_SUCCESS";
export const GET_USER_FROM_TOKEN_FAILURE = "GET_USER_FROM_TOKEN_FAILURE";

export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

export const PASSWORD_RESET_LINK_SENT_SUCCESS = "PASSWORD_RESET_LINK_SENT__SUCCESS";
export const PASSWORD_RESET_LINK_SENT_FAILURE = "PASSWORD_RESET_LINK_SENT__FAILURE";
export const PASSWORD_RESET_LINK_SENT_CLEAR = "PASSWORD_RESET_LINK_SENT__CLEAR";

export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE";
export const CLEAR_PASSWORD_RESET = "CLEAR_PASSWORD_RESET";