export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_FROM_TOKEN_REQUEST = "GET_USER_FROM_TOKEN_REQUEST";
export const GET_USER_FROM_TOKEN_SUCCESS = "GET_USER_FROM_TOKEN_SUCCESS";
export const GET_USER_FROM_TOKEN_FAILURE = "GET_USER_FROM_TOKEN_FAILURE";