export const FETCH_STATISTICS_REQUEST = "FETCH_STATISTICS_REQUEST";
export const FETCH_STATISTICS_SUCCESS = "FETCH_STATISTICS_SUCCESS";
export const FETCH_STATISTICS_FAILURE = "FETCH_STATISTICS_FAILURE";
export const FETCH_SCHEDULE_REQUEST = "FETCH_SCHEDULE_REQUEST";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILURE = "FETCH_SCHEDULE_FAILURE";

export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";

export const ACTIVE_FOOTER_SUBMIT = "ACTIVE_FOOTER_SUBMIT";
export const INACTIVE_FOOTER_SUBMIT = "INACTIVE_FOOTER_SUBMIT";

export const PROCESS_SUBMIT_CLICK =
  "INCREASE_STEPPER_COUNT AND MAKE_THE_BUTTON_INACTIVE";
export const DECREASE_STEPPER_COUNT = "DECREASE_STEPPER_COUNT";

export const RESET_ALL_TEMPLATES = "RESET_ALL_TEMPLATES";
export const SET_ALL_TEMPLATES = "SET_ALL_TEMPLATES";

export const FETCH_ALL_TEMPLATE_BY_CATEGORYID =
  "FETCH_ALL_TEMPLATE_BY_CATEGORYID";

export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const SET_SELECTED_TEMPLATE = "SET_SELECTED_TEMPLATE";

export const FETCH_CURRENT_TEMPLATE_STRUCTURE =
  "FETCH_CURRENT_TEMPLATE_STRUCTURE";

export const ADD_RECIPIENT = "ADD_RECIPIENT";

export const REMOVE_RECIPIENT = "REMOVE_RECIPIENT";

export const ADD_RECIPIENTS = "SET_RECIPIENTS";

export const SET_SELECTED_OPEN_MENU_ID = "SET_SELECTED_OPEN_MENU_ID";

export const SET_CURRENT_SELECTED_RECIPIENT = "SET_CURRENT_SELECTED_RECIPIENT";

export const RESET_STATE = "RESET_STATE";

export const RESET_RECIPIENT = "RESET_RECIPIENT";

export const SET_REGISTER_REQUEST_ID = "SET_REGISTER_REQUEST_ID";

export const SET_UPLOADED_FILE_NAME = "SET_UPLOADED_FILE_NAME";
export const SET_SHOW_DROP_ZONE = "SET_SHOW_DROP_ZONE";

export const SET_PROGRESS = "SET_PROGRESS";

export const RESET_PROGRESS_BAR = "RESET_PROGRESS_BAR";

export const SET_FILE_ANALYZING = "SET_FILE_ANALYZING";
export const SET_FILE_PROCESSING_ERROR = "SET_FILE_PROCESSING_ERROR";

export const SET_FILE_PROCESSING_ERROR_MESSAGE =
  "SET_FILE_PROCESSING_ERROR_MESSAGE";

export const SET_PROFILES_LIST = "SET_PROFILES_LIST";
