export const FETCH_STATISTICS_REQUEST = "FETCH_STATISTICS_REQUEST";
export const FETCH_STATISTICS_SUCCESS = "FETCH_STATISTICS_SUCCESS";
export const FETCH_STATISTICS_FAILURE = "FETCH_STATISTICS_FAILURE";
export const FETCH_SCHEDULE_REQUEST = "FETCH_SCHEDULE_REQUEST";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILURE = "FETCH_SCHEDULE_FAILURE";

export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";

export const ACTIVE_FOOTER_SUBMIT = "ACTIVE_FOOTER_SUBMIT";
export const INACTIVE_FOOTER_SUBMIT = "INACTIVE_FOOTER_SUBMIT";

export const PROCESS_SUBMIT_CLICK =
  "INCREASE_STEPPER_COUNT AND MAKE_THE_BUTTON_INACTIVE";
export const DECREASE_STEPPER_COUNT = "DECREASE_STEPPER_COUNT";

export const RESET_ALL_TEMPLATES = "RESET_ALL_TEMPLATES";
export const SET_ALL_TEMPLATES = "SET_ALL_TEMPLATES";
