export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILURE = "USER_CREATE_FAILURE";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";
export const USER_UPDATE_CLEAN = "USER_UPDATE_CLEAN";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";
export const USER_DELETE_CLEAN = "USER_DELETE_CLEAN";

export const USER_GET_BY_ID_REQUEST = "USER_GET_BY_ID_REQUEST";
export const USER_GET_BY_ID_SUCCESS = "USER_GET_BY_ID_SUCCESS";
export const USER_GET_BY_ID_FAILURE = "USER_GET_BY_ID_FAILURE";
export const USER_GET_BY_ID_CLEAN = "USER_GET_BY_ID_CLEAN";


export const USERS_GET_PAGINATED_REQUEST = "USERS_GET_PAGINATED_REQUEST";
export const USERS_GET_PAGINATED_SUCCESS = "USERS_GET_PAGINATED_SUCCESS";
export const USERS_GET_PAGINATED_FAILURE = "USERS_GET_PAGINATED_FAILURE";

export const ADMINS_GET_REQUEST = "ADMINS_GET_REQUEST";
export const ADMINS_GET_SUCCESS = "ADMINS_GET_SUCCESS";
export const ADMINS_GET_FAILURE = "ADMINS_GET_FAILURE";
export const ADMINS_GET_RESET = "ADMINS_GET_RESET";
export const ADMINS_CLEAN = "ADMINS_CLEAN";

export const USERS_GET_REQUEST = "USERS_GET_REQUEST";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_GET_FAILURE = "USERS_GET_FAILURE";
export const USERS_GET_RESET = "USERS_GET_RESET";
export const USERS_CLEAN = "USERS_CLEAN";

export const LOCKED_GET_REQUEST = "LOCKED_GET_REQUEST";
export const LOCKED_GET_SUCCESS = "LOCKED_GET_SUCCESS";
export const LOCKED_GET_FAILURE = "LOCKED_GET_FAILURE";
export const LOCKED_GET_RESET = "LOCKED_GET_RESET";
export const LOCKED_CLEAN = "LOCKED_CLEAN";

export const PAGE_NUMBER_UPDATE = "PAGE_NUMBER_UPDATE";
export const PAGE_NUMBER_RESET = "PAGE_NUMBER_RESET";
export const HAS_MORE_UPDATE = "HAS_MORE_UPDATE";
export const SORTING_ENABLED_UPDATE = "SORTING_ENABLED_UPDATE";
export const SORTING_TYPE_UPDATE = "SORTING_TYPE_UPDATE";
export const SORTING_TYPE_RESET = "SORTING_TYPE_RESET";

export const ADMINS_SORTED_REQUEST = "ADMINS_SORTED_REQUEST";
export const ADMINS_SORTED_SUCCESS = "ADMINS_SORTED_SUCCESS";
export const ADMINS_SORTED_FAILURE = "ADMINS_SORTED_FAILURE";

export const USERS_SORTED_REQUEST = "USERS_SORTED_REQUEST";
export const USERS_SORTED_SUCCESS = "USERS_SORTED_SUCCESS";
export const USERS_SORTED_FAILURE = "USERS_SORTED_FAILURE";

export const LOCKED_SORTED_REQUEST = "LOCKED_SORTED_REQUEST";
export const LOCKED_SORTED_SUCCESS = "LOCKED_SORTED_SUCCESS";
export const LOCKED_SORTED_FAILURE = "LOCKED_SORTED_FAILURE";

export const USERS_GET_SORTED_REQUEST = "USERS_GET_SORTED_REQUEST";
export const USERS_GET_SORTED_SUCCESS = "USERS_GET_SORTED_SUCCESS";
export const USERS_GET_SORTED_FAILURE = "USERS_GET_SORTED_FAILURE";

export const USERS_LOCK_REQUEST = "USERS_LOCK_REQUEST";
export const USERS_LOCK_SUCCESS = "USERS_LOCK_SUCCESS";
export const USERS_LOCK_FAILURE = "USERS_LOCK_FAILURE";

export const USERS_REMOVE_REQUEST = "USERS_REMOVE_REQUEST";
export const USERS_REMOVE_SUCCESS = "USERS_REMOVE_SUCCESS";
export const USERS_REMOVE_FAILURE = "USERS_REMOVE_FAILURE";

export const USERS_UNLOCK_REQUEST = "USERS_UNLOCK_REQUEST";
export const USERS_UNLOCK_SUCCESS = "USERS_UNLOCK_SUCCESS";
export const USERS_UNLOCK_FAILURE = "USERS_UNLOCK_FAILURE";