export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILURE = "USER_CREATE_FAILURE";
export const USER_CREATE_CLEAN = "USER_CREATE_CLEAN";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";
export const USER_UPDATE_CLEAN = "USER_UPDATE_CLEAN";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";
export const USER_DELETE_CLEAN = "USER_DELETE_CLEAN";

export const USER_GET_BY_ID_REQUEST = "USER_GET_BY_ID_REQUEST";
export const USER_GET_BY_ID_SUCCESS = "USER_GET_BY_ID_SUCCESS";
export const USER_GET_BY_ID_FAILURE = "USER_GET_BY_ID_FAILURE";
export const USER_GET_BY_ID_CLEAN = "USER_GET_BY_ID_CLEAN";

export const USERS_GET_REQUEST = "USERS_GET_REQUEST";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_GET_FAILURE = "USERS_GET_FAILURE";
export const USERS_GET_CLEAN = "USERS_GET_CLEAN";